{
 "title": "Capulse Admission Webhooks Diagnostics",
 "description": "Profiling performance-related metrics based on controller-runtime.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total,job)"
    }
   },
   {
    "name": "Webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=~\"$job\"},webhook)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_panics_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Panic"
    },
    {
     "expr": "sum by (code) (rate(controller_runtime_webhook_requests_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Admission Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (webhook) (rate(controller_runtime_webhook_requests_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Requests In-Flight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (webhook) (rate(controller_runtime_webhook_requests_in_flight{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, webhook) (rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\"}[5m]))\n)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, webhook) (rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\"}[$__rate_interval]))\n)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook Latency Spent Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (webhook) (rate(controller_runtime_webhook_latency_seconds_count{job=\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controller_runtime_webhook_requests_total{job=\"$job\"}\n",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook \"$Webhook\" Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "Webhook"
  },
  {
   "title": "Webhook Request Rate $Webhook",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (webhook) (rate(controller_runtime_webhook_requests_total{job=~\"$job\", webhook=\"$Webhook\"}[$__rate_interval]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum by (code) (rate(controller_runtime_webhook_requests_total{job=~\"$job\",  webhook=\"$Webhook\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency Second Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_latency_seconds_bucket{job=~\"$job\", webhook=\"$Webhook\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}