apiVersion: v1
kind: Pod
metadata:
  name: security-profile-default
  namespace: solar-test
spec:
  os:
    name: linux
  schedulingGates:
    - name: examples.projectcapsule.dev/security-profile
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.10
