- name: Adriano Pezzuto
  github: https://github.com/bsctl
  company: Clastix
  projects:
    - https://github.com/projectcapsule/capsule
    - https://github.com/clastix/capsule-proxy
- name: Dario Tranchitella
  github: https://github.com/prometherion
  company: Clastix
  projects:
    - https://github.com/projectcapsule/capsule
    - https://github.com/clastix/capsule-proxy
- name: Maksim Fedotov
  github: https://github.com/MaxFedotov
  company: wargaming.net
  projects:
    - https://github.com/projectcapsule/capsule
    - https://github.com/clastix/capsule-proxy
- name: Oliver Bähler
  github: https://github.com/oliverbaehler
  company: Peak Scale
  projects:
    - https://github.com/projectcapsule/capsule
- name: Massimiliano Giovagnoli
  github: https://github.com/maxgio92
  company: Proximus
  projects:
    - https://github.com/projectcapsule/capsule
    - https://github.com/projectcapsule/capsule-proxy
