apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2026-07-20T10:49:49Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin-alice
  resourceVersion: "137"
  uid: 8d38227c-7b6d-49e2-a564-61321f6a45bc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice
