---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret-3
  namespace: kube-system
  labels:
    pullsecret.company.com: "true"
data:
  .secret-file: dmFsdWUtMg0KDQo=

---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret-1
  namespace: solar-prod
  labels:
    pullsecret.company.com: "true"
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret-2
  namespace: solar-prod
  labels:
    pullsecret.company.com: "true"
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: capsule.clastix.io/v1beta2
kind: TenantResource
metadata:
  name: tenant-cluster-rbac
  namespace: solar-system
spec:
  resyncPeriod: 5s
  resources:
    - context:
        resources:
          - index: secrets
            apiVersion: v1
            kind: Secret
            namespace: "solar-prod"
            selector:
              matchLabels:
                pullsecret.company.com: "true"
            # Replicate all Configmaps labeled with projectcapsule.dev/replicate: "true"
      generators:
        - missingKey: error
          template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: show-context
            data:
              count: '{{ if $.secrets }}{{ len $.secrets }}{{ else }}0{{ end }}'
              context.yaml: |
                {{- toYAML $.secrets | nindent 4 }}
