# Target Binary
ARG TARGET_IMAGE
FROM ${TARGET_IMAGE} AS target

# Inject Harpoon Image
FROM alegrey91/harpoon:v0.9.4
WORKDIR /
COPY --from=target /ko-app/capsule ./manager

ENTRYPOINT ["/harpoon", \
		"capture", \
		"-f", "main.main", \
		"-E", "NAMESPACE=capsule-system", \
		"-i", "2", \
		"-c", "-e", \
		"-S", "-D", "/tmp/results/", \
		"--", "/manager"]
