apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: global-scope
spec:
  # New
  scope: Tenant


  resyncPeriod: 5s

  # New
  #serviceaccount: 
  #  name: capsule
  #  namespace: capsule-system

  resources:
    - #additionalMetadata:
      #  labels:
      #    "replicated-by": "capsule" 
    
      ignore:
        - paths: ["/data/ui_properties_file_name"]
          target:
            kind: ConfigMap

      context:
        resources:
          - index: "sec"
            apiVersion: v1
            kind: Secret
            name: capsule-tls
            namespace: capsule-system
      force: false

      generators:
        - template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: test-demo
              namespace: default
            data:
              {{ .Tenant.ObjectMeta.Name }}.conf: |
                1

