---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
spec:
  owners:
    - name: alice
      kind: User
  namespaceOptions:
    additionalMetadataList:
      - labels:
          k8s.tenant.corp/name: {{ tenant.name }}
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: tenant-gateway
spec:
  scope: Tenant
  resources:
    - rawItems:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ tenant.name }}-system"
          labels:
            k8s.tenant.corp/name: {{ tenant.name }}
            k8s.tenant.corp/system: {{ tenant.name }}
      generators:
      - template: |
          ---
          apiVersion: gateway.envoyproxy.io/v1alpha1
          kind: EnvoyProxy
          metadata:
            name: "{{ tenant.name }}-managed"
            namespace: "{{ tenant.name }}-system"
          spec:
            logging:
              level:
                default: debug
            provider:
              type: Kubernetes
              kubernetes:
                envoyDeployment:
                {{- if $.tenant.spec.data.loadBalancerIP }}
                envoyService:
                  loadBalancerIP: {{ $.tenant.spec.data.loadBalancerIP }}
                {{- end }}
      - template: |
          ---
          apiVersion: gateway.networking.k8s.io/v1
          kind: Gateway
          metadata:
            name: "{{ tenant.name }}-managed"
            namespace: "{{ tenant.name }}-system"
            {{- if $.tenant.spec.data.managedIssuer }}
            annotations:
              cert-manager.io/issuer: {{ tenant.name }}-managed
              cert-manager.io/private-key-size: "4096"
              cert-manager.io/private-key-algorithm: RSA
            {{- end }}
          spec:
            gatewayClassName: tenants
            infrastructure:
              parametersRef:
                group: gateway.envoyproxy.io
                kind: EnvoyProxy
                name: "{{ tenant.name }}-managed"
            listeners:
              - name: http-challenge
                port: 80
                protocol: HTTP
                hostname: "*.{{ $.tenant.metadata.name }}.cluster.corp.com"
                allowedRoutes:
                  namespaces:
                    from: Selector
                    selector:
                      matchLabels:
                        k8s.tenant.corp/name: {{ $.tenant.metadata.name }}

        



---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: itbs-tenant-{{ $.Values.name }}-gateway
  namespace: itbs-tenant-{{ $.Values.name }}-system
spec:
  logging:
    level:
      default: debug
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      {{- if $.Values.networking.gateway.loadbalancer }}
      envoyService:
        loadBalancerIP: {{ $.Values.networking.ingress.loadbalancer }}
      {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: itbs-tenant-{{ $.Values.name }}-gateway
  namespace: itbs-tenant-{{ $.Values.name }}-system
  {{- if $.Values.networking.gateway.issuer.enabled }}
  annotations:
    cert-manager.io/issuer: itbs-tenant-{{ $.Values.name }}-http
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-algorithm: RSA
  {{- end }}
spec:
  gatewayClassName: {{$.Values.cluster.gateway.classes.platform}}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: itbs-tenant-{{ $.Values.name }}-gateway
  listeners:
    - name: http-challenge
      port: 80
      protocol: HTTP
      hostname: "*.{{ $.Values.name }}.{{ $.Values.cluster.name }}.{{ $.Values.infrastructure.dns.zone }}"
      allowedRoutes:  # Only this tenant's capsule namespaces can attach routes to this listener
        namespaces:
          from: Selector
          selector:
            matchLabels:
              tenant.itbs.ch/tenant: "{{ $.Values.name }}"

    {{- if $.Values.metrics.enabled }}
    - name: https-alertmanager
      protocol: HTTPS
      port: 443
      hostname: "alertmanager.{{ $.Values.name }}.{{ .Values.cluster.name }}.{{ .Values.infrastructure.dns.zone }}"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: alertmanager-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              tenant.itbs.ch/tenant-system: "{{ $.Values.name }}"
    - name: https-prometheus
      protocol: HTTPS
      port: 443
      hostname: "prometheus.{{ $.Values.name }}.{{ .Values.cluster.name }}.{{ .Values.infrastructure.dns.zone }}"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: prometheus-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              tenant.itbs.ch/tenant-system: "{{ $.Values.name }}"
    {{- end }}
    {{- if $.Values.grafana.enabled }}
    - name: https-grafana
      protocol: HTTPS
      port: 443
      hostname: "grafana.{{ $.Values.name }}.{{ .Values.cluster.name }}.{{ .Values.infrastructure.dns.zone }}"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: grafana-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              tenant.itbs.ch/tenant-system: "{{ $.Values.name }}"
    {{- end }}


      
      
      apiVersion: v1
        kind: LimitRange
        metadata:
          name: "{{tenant.name}}-{{namespace}}-resource-constraint"
        spec:
          limits:
          - default: # this section defines default limits
              cpu: 500m
            defaultRequest: # this section defines default requests
              cpu: 500m
            max: # max and min define the limit range
              cpu: "1"
            min:
              cpu: 100m
            type: Container

    - #additionalMetadata:
      #  labels:
      #    "replicated-by": "capsule"
      force: true
      context:
        resources:
          - index: "sec"
            apiVersion: v1
            kind: Secret
            name: capsule-tls
      templates:
        - template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: test-demo
              namespace: default
            data:
              {{ .Tenant.ObjectMeta.Name }}.conf: |
                1
    - force: true
      context:
        resources:
          - index: "sec"
            apiVersion: v1
            kind: Secret
            name: capsule-tls
