---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capsule-default-global
rules:
- apiGroups: [""]
  resources: ["limitranges", "secrets", "configmaps"]
  verbs: ["get", "patch", "create", "delete"]
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies"]
  verbs: ["get", "patch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capsule-default-global
subjects:
- kind: ServiceAccount
  name: capsule-default-global
  namespace: capsule-system
roleRef:
  kind: ClusterRole
  name: capsule-default-global
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
spec:
  owners:
    - name: alice
      kind: User
  data:
    registries:
      - name: "dockerhub"
        target: "index.docker.io"
        rewrite: "harbor.odc.nord/solar-k8s/"
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: tenant-registry-rewrite
spec:
  resyncPeriod: 5s
  serviceAccount:
    name: capsule-default-global
    namespace: capsule-system
  scope: Tenant
  resources:
    - generators:
        - template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: show-context-2
            data:
              context.yaml: |
                {{- toYAML $.tenant.spec.data.registries | nindent 4 }} 

    - generators:
      - template: |
          {{- if $.tenant.spec.data }}
            {{- if $.tenant.spec.data.registries }}
          ---
          apiVersion: kyverno.io/v1
          kind: ClusterPolicy
          metadata:
            name: {{$.tenant.metadata.name}}-image-replacements
          spec:
            rules:
            {{- range $.tenant.spec.data.registries }}
              - name: redirect-{{.name}}
                match:
                  any:
                    - resources:
                        kinds:
                          - Pod
                        operations:
                          - CREATE
                          - UPDATE
                mutate:
                  foreach:
                    - list: request.object.spec.initContainers[]
                      context:
                        - name: imageData
                          imageRegistry:
                            reference: "{{ "{{ element.image }}" }}"
                      preconditions:
                        any:
                          - key: "{{ "{{ imageData.registry }}" }}"
                            operator: Equals
                            value: "{{.target}}"
                      patchStrategicMerge:
                        spec:
                          initContainers:
                            - name: "{{ "{{ element.name }}" }}"
                              image: {{.rewrite}}/{{ "{{ imageData.repository }}" }}:{{ "{{ imageData.identifier }}" }}
                    - list: request.object.spec.containers[]
                      context:
                        - name: imageData
                          imageRegistry:
                            reference: "{{ "{{ element.image }}" }}"
                      preconditions:
                        any:
                          - key: "{{ "{{ imageData.registry }}" }}"
                            operator: Equals
                            value: {{.target}}
                      patchStrategicMerge:
                        spec:
                          containers:
                            - name: "{{ "{{ element.name }}" }}"
                              image: {{.rewrite}}/{{ "{{ imageData.repository }}" }}:{{ "{{ imageData.identifier }}" }}
              {{- end }}
            {{- end }}
          {{- end }}