apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  labels:
    team: platform
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 2Gi
