---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-2
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"

