---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalCustomQuota
metadata:
  name: pvc-storage-limit
spec:
  limit: "5"
  sources:
    - group: ""
      version: v1
      kind: Pod
      path: ".spec.containers[*].resources.limits.cpu"
    - group: ""
      version: v1
      kind: Pod
      path: ".spec.initContainers[*].resources.limits.cpu"
      op: sub
  namespaceSelectors:
    - matchLabels:
        capsule.clastix.io/tenant: solar

