---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-green-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capsule-gateway-manager
  namespace: tenant-green-system
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capsule-gateway-manager
  namespace: tenant-green-system
subjects:
  - kind: ServiceAccount
    name: capsule
    namespace: capsule-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capsule-gateway-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-solar-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capsule-gateway-manager
  namespace: tenant-solar-system
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capsule-gateway-manager
  namespace: tenant-solar-system
subjects:
  - kind: ServiceAccount
    name: capsule
    namespace: capsule-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capsule-gateway-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-wind-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capsule-gateway-manager
  namespace: tenant-wind-system
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capsule-gateway-manager
  namespace: tenant-wind-system
subjects:
  - kind: ServiceAccount
    name: capsule
    namespace: capsule-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capsule-gateway-manager
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: online-boutique
  namespace: solar-test
spec:
  hostnames:
  - boutique.app.example.ch
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: tenant-wind-gateway
    namespace: tenant-wind-system
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 301
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: online-boutique-checkout
  namespace: solar-prod
spec:
  hostnames:
  - checkout.boutique.app.example.ch
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: tenant-solar-gateway
    namespace: tenant-solar-system
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 301
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /
