apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: renewable-pull-secrets
spec:
  tenantSelector: {}
  resyncPeriod: 5s
  scope: Tenant
  resources:
    - additionalMetadata:
        labels:
          "replicated-by": "capsule"
      rawItems:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "meow-system"
