apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: renewable-pull-secrets
spec:
  tenantSelector:
    matchLabels:
       energy: renewable
  resyncPeriod: 5s
  resources:
    - templates:
        resources:
          - index: "sec"
            apiVersion: v1
            kind: Secret
        items:
          - |
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: "some-secret-bruv"
            stringData:
              username: "some-username"
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: "the-context"
            data:
              context: |
                {{ . | toYaml | nindent 4}}


