---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: solar-test
  labels:
    app: netshoot
spec:
  initContainers:
    - name: netshoot-3
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      restartPolicy: Never
      resources:
        limits:
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  containers:
    - name: netshoot
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        limits:
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    - name: netshoot-2
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        limits:
          cpu: "2"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-2
  namespace: solar-test
  labels:
    app: netshoot
spec:
  containers:
    - name: netshoot
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        limits:
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    - name: netshoot-2
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        limits:
          cpu: "2"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
