---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: argo-cd-permission
spec:
  scope: Tenant
  settings:
    adopt: true
  resources:
    - generators:
        - template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: {{$.tenant.metadata.name}}-show-context
              namespace: capsule-system
            data:
              context.yaml: |
                {{- toYAML $.tenant.rbac | nindent 4 }}      
