---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-metrics
  labels:
    app: external-metrics
subsets:
- addresses:
  - ip: "${LAPTOP_HOST_IP}"
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-metrics
  namespace: capsule-system
  labels:
    app: external-metrics
spec:
  type: ExternalName
  externalName: "${LAPTOP_HOST_IP}"
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-metrics-servicemonitor
spec:
  selector:
    matchLabels:
      app: "external-metrics"
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
