{
 "title": "Controller Runtime Webhooks Detail",
 "description": "Profiling performance-related metrics based on controller-runtime.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total,job)"
    }
   },
   {
    "name": "Webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=~\"$job\"},webhook)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=~\"$job\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reoncile Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (result) (rate(controller_runtime_reconcile_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Webhook \"$Webhook\" Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "Webhook"
  },
  {
   "title": "Webhook Request Rate $Webhook",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_latency_seconds_count{job=~\"$job\", webhook=\"$Webhook\"}[$__rate_interval])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Reconcile Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_latency_seconds_bucket{job=~\"$job\", webhook=\"$Webhook\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}