{
 "title": "Controller Runtime Controllers Detail",
 "description": "Profiling performance-related metrics based on controller-runtime.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(controller_runtime_active_workers,job)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{job=~\"$job\"},controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=~\"$job\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum (controller_runtime_active_workers{job=~\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Reoncile Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (result) (\n  increase(controller_runtime_reconcile_total{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "sum(\n  increase(controller_runtime_reconcile_total{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Controller \"$Controller\" Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "Controller"
  },
  {
   "title": "Reconcile Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (result) (\n  increase(controller_runtime_reconcile_total{job=~\"$job\", controller=~\"$Controller\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{job=~'$job', controller=~'$Controller'}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}