{
 "title": "Golang Monitoring - Echo & GORM",
 "description": "This production-ready dashboard provides full-stack visibility for Golang applications using Echo framework and GORM ORM. Monitor critical application metrics including HTTP performance, memory allocation patterns, garbage collection efficiency, and database connection pooling. Features intelligent Apdex scoring, live request tracing, and resource utilization trends with built-in alert thresholds. Perfect for DevOps teams managing high-performance Golang microservices.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   { "name": "target", "label": "Target", "query": "0.05,0.1,0.2,0.3,0.4,0.5" },
   { "name": "tolerated", "label": "Tolerated", "query": "0.1,0.2,0.3,0.4,0.5" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarts in $interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex Score: $target s, $tolerated s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(echo_request_duration_seconds_bucket{le=\"$target\", code=~\"^2..$\", instance=~\"$instance\"})\n        + (\n            sum(echo_request_duration_seconds_bucket{le=\"$tolerated\", code=~\"^2..$\", instance=~\"$instance\"})\n            - sum(echo_request_duration_seconds_bucket{le=\"$target\", code=~\"^2..$\", instance=~\"$instance\"})\n        ) / 2\n    ) / sum(echo_request_duration_seconds_count{instance=~\"$instance\", code=~\"^2..$\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(echo_request_duration_seconds_count{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(echo_request_duration_seconds_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(echo_request_duration_seconds_count{instance=~\"$instance\", code=~\"^[45]..$\"} OR on() vector(0))\n    / sum(echo_request_duration_seconds_count{instance=~\"$instance\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(echo_request_size_bytes_sum{instance=~\"$instance\"}) + sum(echo_response_size_bytes_sum{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(echo_request_size_bytes_sum{instance=~\"$instance\"}[$interval])) + sum(rate(echo_response_size_bytes_sum{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(go_goroutines{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: goroutines (avg)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_threads{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_memstats_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} (avg)"
    },
    {
     "expr": "deriv(go_memstats_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} (deriv)"
    }
   ]
  },
  {
   "title": "Stack Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_memstats_stack_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: stack in use (avg)"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: stack in use (deriv)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_memstats_mspan_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: mspan (avg)"
    },
    {
     "expr": "deriv(go_memstats_mspan_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: mspan (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_mcache_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: mcache (avg)"
    },
    {
     "expr": "deriv(go_memstats_mcache_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: mcache (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: buck hash (avg)"
    },
    {
     "expr": "deriv(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: buck hash (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_gc_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: gc (avg)"
    },
    {
     "expr": "deriv(go_memstats_gc_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: gc (deriv)"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_memstats_heap_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: heap reserved (avg)"
    },
    {
     "expr": "deriv(go_memstats_heap_sys_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: heap reserved (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_heap_inuse_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: heap in use (avg)"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: heap in use (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_heap_alloc_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: heap alloc (avg)"
    },
    {
     "expr": "deriv(go_memstats_heap_alloc_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: heap alloc (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_heap_idle_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: heap idle (avg)"
    },
    {
     "expr": "deriv(go_memstats_heap_idle_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: heap idle (deriv)"
    },
    {
     "expr": "avg by(instance)(go_memstats_heap_released_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: heap released (avg)"
    },
    {
     "expr": "deriv(go_memstats_heap_released_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: heap released (deriv)"
    }
   ]
  },
  {
   "title": "Heap Alloc By Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(le) (rate(go_gc_heap_allocs_by_size_bytes_bucket{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Frees By Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(le)(rate(go_gc_heap_frees_by_size_bytes_bucket{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes (IEC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: obj mallocs/s"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(instance)(\n    go_memstats_mallocs_total{instance=~\"$instance\"}\n    - go_memstats_frees_total{instance=~\"$instance\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: resident memory (avg)"
    },
    {
     "expr": "deriv(hypr_process_resident_memory_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: resident memory (deriv)"
    },
    {
     "expr": "avg by(instance)(hypr_process_virtual_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: virtual memory (avg)"
    },
    {
     "expr": "deriv(hypr_process_virtual_memory_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: virtual memory (deriv)"
    }
   ]
  },
  { "title": "Go Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_gc_duration_seconds{quantile=\"0.0\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: min gc time (avg)"
    },
    {
     "expr": "avg by(instance)(go_gc_duration_seconds{quantile=\"1.0\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: max gc time (avg)"
    },
    {
     "expr": "avg by(instance)(go_gc_duration_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: gc duration (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes (IEC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance)(go_memstats_next_gc_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(le)(rate(go_gc_pauses_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pointer Deferences",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "avg(go_memstats_lookups_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}: pointer deferences (avg)"
    }
   ]
  },
  { "title": "Go File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "avg(process_open_fds{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}} (avg)"
    },
    {
     "expr": "deriv(process_open_fds{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} (deriv)"
    }
   ]
  },
  {
   "title": "File Descriptor Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_open_fds{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(process_max_fds{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Echo Framework", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Apdex Score: $target s, $tolerated s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(echo_request_duration_seconds_bucket{le=\"$target\", code=~\"^2..$\", instance=~\"$instance\"}) by (instance)\n        + (\n            sum(echo_request_duration_seconds_bucket{le=\"$tolerated\", code=~\"^2..$\", instance=~\"$instance\"}) by (instance)\n            - sum(echo_request_duration_seconds_bucket{le=\"$target\", code=~\"^2..$\", instance=~\"$instance\"}) by (instance)\n        ) / 2\n    ) / sum(echo_request_duration_seconds_count{instance=~\"$instance\", code=~\"^2..$\"}) by (instance)\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (code, le))",
     "legendFormat": "{{code}} (95%)"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(echo_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (code, le))",
     "legendFormat": "{{code}} (100%)"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(echo_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Code Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(echo_request_duration_seconds_count{instance=~\"$instance\"}) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(echo_request_size_bytes_sum{instance=~\"$instance\"}) by (code, method, url)",
     "legendFormat": "{{method}} {{url}} {{code}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(echo_request_duration_seconds_count{instance=~\"$instance\"}) by (url)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Request Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_sum{instance=~\"$instance\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_sum{instance=~\"$instance\", code=~\"^[23]..$\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_sum{instance=~\"$instance\", code=~\"^[54]..$\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_count{instance=~\"$instance\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_count{instance=~\"$instance\", code=~\"^[23]..$\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(echo_request_duration_seconds_count{instance=~\"$instance\", code=~\"^[54]..$\"}) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "GORM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Connections",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 792 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(go_sql_max_open_connections{instance=~\"$instance\"}) by (db_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(go_sql_open_connections{instance=~\"$instance\"}) by (db_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database Connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 21, "x": 3, "y": 792 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(go_sql_idle_connections{instance=~\"$instance\"}) by (instance, db_name)",
       "legendFormat": "{{instance}}: {{db_name}} idle connections (avg)"
      },
      {
       "expr": "avg(go_sql_in_use_connections{instance=~\"$instance\"}) by (instance, db_name)",
       "legendFormat": "{{instance}}: {{db_name}} in use connections (avg)"
      }
     ]
    }
   ]
  }
 ]
}