{
 "title": "capsule",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "controller_name",
    "label": "Controller name",
    "query": {
     "query": "label_values(controller_runtime_active_workers{job=\"capsule\"},controller)"
    }
   },
   {
    "name": "rest_client_url",
    "label": "REST client URL",
    "query": {
     "query": "label_values(rest_client_request_latency_seconds_sum{job=\"capsule\"},url)"
    }
   },
   {
    "name": "rest_client_verb",
    "label": "REST client verb",
    "query": {
     "query": "label_values(rest_client_request_latency_seconds_sum{job=\"capsule\"},verb)"
    }
   },
   {
    "name": "webhook",
    "label": "Webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_latency_seconds_sum{job=\"capsule\"}, webhook)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Manager controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$controller_name reconcile latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "controller_name",
   "targets": [
    {
     "expr": "sum by (le) (increase(workqueue_work_duration_seconds_bucket{job=\"capsule\", name=\"$controller_name\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Webhook error rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
     "repeat": "webhook",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "$webhook status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(controller_runtime_webhook_requests_total{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval])) by (webhook, code)",
       "legendFormat": "{{ code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Webhooks latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "repeat": "webhook",
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$webhook reconcile latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum by (le) (increase(controller_runtime_webhook_latency_seconds_bucket{job=\"capsule\", webhook=\"$webhook\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "REST client latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency for ${rest_client_url:raw}",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "repeat": "rest_client_url",
     "targets": [
      {
       "expr": "sum by (le) (increase(rest_client_request_latency_seconds_bucket{job=\"capsule\", url=\"${rest_client_url:raw}\", verb=\"$rest_client_verb\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Latency for ${rest_client_url:raw}",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (increase(rest_client_request_latency_seconds_bucket{job=\"capsule\", url=\"${rest_client_url:raw}\", verb=\"$rest_client_verb\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Latency for ${rest_client_url:raw}",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (increase(rest_client_request_latency_seconds_bucket{job=\"capsule\", url=\"${rest_client_url:raw}\", verb=\"$rest_client_verb\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Latency for ${rest_client_url:raw}",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (increase(rest_client_request_latency_seconds_bucket{job=\"capsule\", url=\"${rest_client_url:raw}\", verb=\"$rest_client_verb\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST client error rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST Client status code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(irate(rest_client_requests_total{job=\"capsule\"}[$__rate_interval])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Rate & Errors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(rest_client_requests_total{job=\"capsule\"}[$__rate_interval])) by (code)",
       "legendFormat": " {{ code }}"
      }
     ]
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"capsule\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"capsule\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"capsule\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"capsule\"})",
     "legendFormat": "Active Controllers"
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue latency",
     "type": "stat",
     "description": "service time to complete needed actions",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"capsule\"}[$__rate_interval])) by (instance, name, le))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue rate",
     "type": "stat",
     "description": "number of actions per unit time",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{job=\"capsule\"}[$__rate_interval])) by (instance, name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue depth",
     "type": "stat",
     "description": "number of actions waiting in the queue to be performed",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_depth{job=\"capsule\"}[$__rate_interval])) by (instance, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}