# This rule is not used by the project capsule itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the capsule.clastix.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: capsule
    app.kubernetes.io/managed-by: kustomize
  name: resourcequotaclaim-editor-role
rules:
- apiGroups:
  - capsule.clastix.io
  resources:
  - resourcequotaclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capsule.clastix.io
  resources:
  - resourcequotaclaims/status
  verbs:
  - get
