//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package breaktheglass

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntity) DeepCopyInto(out *AccessEntity) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntity.
func (in *AccessEntity) DeepCopy() *AccessEntity {
	if in == nil {
		return nil
	}
	out := new(AccessEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatusConditionItem) DeepCopyInto(out *BreakRequestStatusConditionItem) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	in.Reviewer.DeepCopyInto(&out.Reviewer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatusConditionItem.
func (in *BreakRequestStatusConditionItem) DeepCopy() *BreakRequestStatusConditionItem {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatusConditionItem)
	in.DeepCopyInto(out)
	return out
}
