//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package breaktheglass

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateItem) DeepCopyInto(out *TemplateItem) {
	*out = *in
	in.ManifestTemplate.DeepCopyInto(&out.ManifestTemplate)
	in.ParamSchema.DeepCopyInto(&out.ParamSchema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateItem.
func (in *TemplateItem) DeepCopy() *TemplateItem {
	if in == nil {
		return nil
	}
	out := new(TemplateItem)
	in.DeepCopyInto(out)
	return out
}
