//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package rules

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleBodyNamespace) DeepCopyInto(out *NamespaceRuleBodyNamespace) {
	*out = *in
	if in.Enforce != nil {
		in, out := &in.Enforce, &out.Enforce
		*out = new(NamespaceRuleEnforceBody)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleBodyNamespace.
func (in *NamespaceRuleBodyNamespace) DeepCopy() *NamespaceRuleBodyNamespace {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleBodyNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleBodyTenant) DeepCopyInto(out *NamespaceRuleBodyTenant) {
	*out = *in
	if in.NamespaceRuleBodyNamespace != nil {
		in, out := &in.NamespaceRuleBodyNamespace, &out.NamespaceRuleBodyNamespace
		*out = new(NamespaceRuleBodyNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Permissions.DeepCopyInto(&out.Permissions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleBodyTenant.
func (in *NamespaceRuleBodyTenant) DeepCopy() *NamespaceRuleBodyTenant {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleBodyTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceBody) DeepCopyInto(out *NamespaceRuleEnforceBody) {
	*out = *in
	in.Workloads.DeepCopyInto(&out.Workloads)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceBody.
func (in *NamespaceRuleEnforceBody) DeepCopy() *NamespaceRuleEnforceBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceWorkloadsBody) DeepCopyInto(out *NamespaceRuleEnforceWorkloadsBody) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]WorkloadValidationTarget, len(*in))
		copy(*out, *in)
	}
	if in.QoSClasses != nil {
		in, out := &in.QoSClasses, &out.QoSClasses
		*out = make([]v1.PodQOSClass, len(*in))
		copy(*out, *in)
	}
	if in.Registries != nil {
		in, out := &in.Registries, &out.Registries
		*out = make([]OCIRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceWorkloadsBody.
func (in *NamespaceRuleEnforceWorkloadsBody) DeepCopy() *NamespaceRuleEnforceWorkloadsBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceWorkloadsBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRulePermissionBody) DeepCopyInto(out *NamespaceRulePermissionBody) {
	*out = *in
	if in.Promotions != nil {
		in, out := &in.Promotions, &out.Promotions
		*out = make([]*NamespaceRulePromotionRule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NamespaceRulePromotionRule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRulePermissionBody.
func (in *NamespaceRulePermissionBody) DeepCopy() *NamespaceRulePermissionBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRulePermissionBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRulePromotionRule) DeepCopyInto(out *NamespaceRulePromotionRule) {
	*out = *in
	if in.ClusterRoles != nil {
		in, out := &in.ClusterRoles, &out.ClusterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRulePromotionRule.
func (in *NamespaceRulePromotionRule) DeepCopy() *NamespaceRulePromotionRule {
	if in == nil {
		return nil
	}
	out := new(NamespaceRulePromotionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIRegistry) DeepCopyInto(out *OCIRegistry) {
	*out = *in
	out.RegExpression = in.RegExpression
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]v1.PullPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIRegistry.
func (in *OCIRegistry) DeepCopy() *OCIRegistry {
	if in == nil {
		return nil
	}
	out := new(OCIRegistry)
	in.DeepCopyInto(out)
	return out
}
