//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package rules

import (
	"github.com/projectcapsule/capsule/pkg/api/rbac"
	"github.com/projectcapsule/capsule/pkg/api/runtime"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionCondition) DeepCopyInto(out *AdmissionCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionCondition.
func (in *AdmissionCondition) DeepCopy() *AdmissionCondition {
	if in == nil {
		return nil
	}
	out := new(AdmissionCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Audience) DeepCopyInto(out *Audience) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Audience.
func (in *Audience) DeepCopy() *Audience {
	if in == nil {
		return nil
	}
	out := new(Audience)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataRule) DeepCopyInto(out *MetadataRule) {
	*out = *in
	in.VersionKinds.DeepCopyInto(&out.VersionKinds)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]MetadataValueRule, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]MetadataValueRule, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataRule.
func (in *MetadataRule) DeepCopy() *MetadataRule {
	if in == nil {
		return nil
	}
	out := new(MetadataRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataValueRule) DeepCopyInto(out *MetadataValueRule) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]runtime.ExpressionMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataValueRule.
func (in *MetadataValueRule) DeepCopy() *MetadataValueRule {
	if in == nil {
		return nil
	}
	out := new(MetadataValueRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleBodyNamespace) DeepCopyInto(out *NamespaceRuleBodyNamespace) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = make([]Audience, len(*in))
		copy(*out, *in)
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = make([]ResourceQuotaRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mutate != nil {
		in, out := &in.Mutate, &out.Mutate
		*out = make([]NamespaceRuleMutation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enforce != nil {
		in, out := &in.Enforce, &out.Enforce
		*out = new(NamespaceRuleEnforceBody)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleBodyNamespace.
func (in *NamespaceRuleBodyNamespace) DeepCopy() *NamespaceRuleBodyNamespace {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleBodyNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleBodyTenant) DeepCopyInto(out *NamespaceRuleBodyTenant) {
	*out = *in
	if in.NamespaceRuleBodyNamespace != nil {
		in, out := &in.NamespaceRuleBodyNamespace, &out.NamespaceRuleBodyNamespace
		*out = new(NamespaceRuleBodyNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Permissions.DeepCopyInto(&out.Permissions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleBodyTenant.
func (in *NamespaceRuleBodyTenant) DeepCopy() *NamespaceRuleBodyTenant {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleBodyTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceBody) DeepCopyInto(out *NamespaceRuleEnforceBody) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AdmissionCondition, len(*in))
		copy(*out, *in)
	}
	in.Workloads.DeepCopyInto(&out.Workloads)
	in.Services.DeepCopyInto(&out.Services)
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceBody.
func (in *NamespaceRuleEnforceBody) DeepCopy() *NamespaceRuleEnforceBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceIngressBody) DeepCopyInto(out *NamespaceRuleEnforceIngressBody) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]IngressType, len(*in))
		copy(*out, *in)
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]runtime.ExpressionMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceIngressBody.
func (in *NamespaceRuleEnforceIngressBody) DeepCopy() *NamespaceRuleEnforceIngressBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceIngressBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceServicesBody) DeepCopyInto(out *NamespaceRuleEnforceServicesBody) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]ServiceType, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = new(ServiceLoadBalancerRule)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = new(ServiceExternalIPRule)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalNames != nil {
		in, out := &in.ExternalNames, &out.ExternalNames
		*out = new(ServiceExternalNameRule)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePorts != nil {
		in, out := &in.NodePorts, &out.NodePorts
		*out = new(ServiceNodePortRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceServicesBody.
func (in *NamespaceRuleEnforceServicesBody) DeepCopy() *NamespaceRuleEnforceServicesBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceServicesBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleEnforceWorkloadsBody) DeepCopyInto(out *NamespaceRuleEnforceWorkloadsBody) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]WorkloadValidationTarget, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make([]WorkloadNodeSelectorMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]WorkloadTolerationMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]WorkloadTopologySpreadMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = make([]WorkloadAffinityMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(WorkloadResourceRules)
		(*in).DeepCopyInto(*out)
	}
	if in.QoSClasses != nil {
		in, out := &in.QoSClasses, &out.QoSClasses
		*out = make([]v1.PodQOSClass, len(*in))
		copy(*out, *in)
	}
	if in.Registries != nil {
		in, out := &in.Registries, &out.Registries
		*out = make([]OCIRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedulers != nil {
		in, out := &in.Schedulers, &out.Schedulers
		*out = make([]runtime.ExpressionMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleEnforceWorkloadsBody.
func (in *NamespaceRuleEnforceWorkloadsBody) DeepCopy() *NamespaceRuleEnforceWorkloadsBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleEnforceWorkloadsBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRuleMutation) DeepCopyInto(out *NamespaceRuleMutation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AdmissionCondition, len(*in))
		copy(*out, *in)
	}
	in.Workloads.DeepCopyInto(&out.Workloads)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRuleMutation.
func (in *NamespaceRuleMutation) DeepCopy() *NamespaceRuleMutation {
	if in == nil {
		return nil
	}
	out := new(NamespaceRuleMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRulePermissionBody) DeepCopyInto(out *NamespaceRulePermissionBody) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]rbac.AdditionalRoleBindingsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Promotions != nil {
		in, out := &in.Promotions, &out.Promotions
		*out = make([]*NamespaceRulePromotionRule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NamespaceRulePromotionRule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRulePermissionBody.
func (in *NamespaceRulePermissionBody) DeepCopy() *NamespaceRulePermissionBody {
	if in == nil {
		return nil
	}
	out := new(NamespaceRulePermissionBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRulePromotionRule) DeepCopyInto(out *NamespaceRulePromotionRule) {
	*out = *in
	if in.ClusterRoles != nil {
		in, out := &in.ClusterRoles, &out.ClusterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRulePromotionRule.
func (in *NamespaceRulePromotionRule) DeepCopy() *NamespaceRulePromotionRule {
	if in == nil {
		return nil
	}
	out := new(NamespaceRulePromotionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIRegistry) DeepCopyInto(out *OCIRegistry) {
	*out = *in
	in.ExpressionMatch.DeepCopyInto(&out.ExpressionMatch)
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]v1.PullPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIRegistry.
func (in *OCIRegistry) DeepCopy() *OCIRegistry {
	if in == nil {
		return nil
	}
	out := new(OCIRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementExpressionMatch) DeepCopyInto(out *PlacementExpressionMatch) {
	*out = *in
	out.ExpressionRegex = in.ExpressionRegex
	if in.Exact != nil {
		in, out := &in.Exact, &out.Exact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementExpressionMatch.
func (in *PlacementExpressionMatch) DeepCopy() *PlacementExpressionMatch {
	if in == nil {
		return nil
	}
	out := new(PlacementExpressionMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementLabelSelectorMatch) DeepCopyInto(out *PlacementLabelSelectorMatch) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]PlacementRequirementMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementLabelSelectorMatch.
func (in *PlacementLabelSelectorMatch) DeepCopy() *PlacementLabelSelectorMatch {
	if in == nil {
		return nil
	}
	out := new(PlacementLabelSelectorMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRange) DeepCopyInto(out *PlacementRange) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRange.
func (in *PlacementRange) DeepCopy() *PlacementRange {
	if in == nil {
		return nil
	}
	out := new(PlacementRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRequirementMatch) DeepCopyInto(out *PlacementRequirementMatch) {
	*out = *in
	in.WorkloadNodeSelectorMatch.DeepCopyInto(&out.WorkloadNodeSelectorMatch)
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]v1.NodeSelectorOperator, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRequirementMatch.
func (in *PlacementRequirementMatch) DeepCopy() *PlacementRequirementMatch {
	if in == nil {
		return nil
	}
	out := new(PlacementRequirementMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaRule) DeepCopyInto(out *ResourceQuotaRule) {
	*out = *in
	in.ResourceQuotaSpec.DeepCopyInto(&out.ResourceQuotaSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaRule.
func (in *ResourceQuotaRule) DeepCopy() *ResourceQuotaRule {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExternalIPRule) DeepCopyInto(out *ServiceExternalIPRule) {
	*out = *in
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExternalIPRule.
func (in *ServiceExternalIPRule) DeepCopy() *ServiceExternalIPRule {
	if in == nil {
		return nil
	}
	out := new(ServiceExternalIPRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExternalNameRule) DeepCopyInto(out *ServiceExternalNameRule) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]runtime.ExpressionMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExternalNameRule.
func (in *ServiceExternalNameRule) DeepCopy() *ServiceExternalNameRule {
	if in == nil {
		return nil
	}
	out := new(ServiceExternalNameRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLoadBalancerRule) DeepCopyInto(out *ServiceLoadBalancerRule) {
	*out = *in
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLoadBalancerRule.
func (in *ServiceLoadBalancerRule) DeepCopy() *ServiceLoadBalancerRule {
	if in == nil {
		return nil
	}
	out := new(ServiceLoadBalancerRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNodePortRange) DeepCopyInto(out *ServiceNodePortRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNodePortRange.
func (in *ServiceNodePortRange) DeepCopy() *ServiceNodePortRange {
	if in == nil {
		return nil
	}
	out := new(ServiceNodePortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNodePortRule) DeepCopyInto(out *ServiceNodePortRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ServiceNodePortRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNodePortRule.
func (in *ServiceNodePortRule) DeepCopy() *ServiceNodePortRule {
	if in == nil {
		return nil
	}
	out := new(ServiceNodePortRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TolerationDurationMatch) DeepCopyInto(out *TolerationDurationMatch) {
	*out = *in
	in.PlacementRange.DeepCopyInto(&out.PlacementRange)
	if in.AllowUnlimited != nil {
		in, out := &in.AllowUnlimited, &out.AllowUnlimited
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TolerationDurationMatch.
func (in *TolerationDurationMatch) DeepCopy() *TolerationDurationMatch {
	if in == nil {
		return nil
	}
	out := new(TolerationDurationMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAffinityMatch) DeepCopyInto(out *WorkloadAffinityMatch) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]PlacementAffinityType, len(*in))
		copy(*out, *in)
	}
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]PlacementAffinityMode, len(*in))
		copy(*out, *in)
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(PlacementRange)
		(*in).DeepCopyInto(*out)
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]PlacementRequirementMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FieldRequirements != nil {
		in, out := &in.FieldRequirements, &out.FieldRequirements
		*out = make([]PlacementRequirementMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologyKey != nil {
		in, out := &in.TopologyKey, &out.TopologyKey
		*out = new(PlacementExpressionMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(PlacementExpressionMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(PlacementLabelSelectorMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(PlacementLabelSelectorMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAffinityMatch.
func (in *WorkloadAffinityMatch) DeepCopy() *WorkloadAffinityMatch {
	if in == nil {
		return nil
	}
	out := new(WorkloadAffinityMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadMutation) DeepCopyInto(out *WorkloadMutation) {
	*out = *in
	if in.HostUsers != nil {
		in, out := &in.HostUsers, &out.HostUsers
		*out = new(bool)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadMutation.
func (in *WorkloadMutation) DeepCopy() *WorkloadMutation {
	if in == nil {
		return nil
	}
	out := new(WorkloadMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNodeSelectorMatch) DeepCopyInto(out *WorkloadNodeSelectorMatch) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(PlacementExpressionMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(PlacementExpressionMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNodeSelectorMatch.
func (in *WorkloadNodeSelectorMatch) DeepCopy() *WorkloadNodeSelectorMatch {
	if in == nil {
		return nil
	}
	out := new(WorkloadNodeSelectorMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceLimitPolicy) DeepCopyInto(out *WorkloadResourceLimitPolicy) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceLimitPolicy.
func (in *WorkloadResourceLimitPolicy) DeepCopy() *WorkloadResourceLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceRequestPolicy) DeepCopyInto(out *WorkloadResourceRequestPolicy) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceRequestPolicy.
func (in *WorkloadResourceRequestPolicy) DeepCopy() *WorkloadResourceRequestPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceRequestPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceRules) DeepCopyInto(out *WorkloadResourceRules) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[v1.ResourceName]WorkloadResourceRequestPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[v1.ResourceName]WorkloadResourceLimitPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceRules.
func (in *WorkloadResourceRules) DeepCopy() *WorkloadResourceRules {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTolerationMatch) DeepCopyInto(out *WorkloadTolerationMatch) {
	*out = *in
	in.WorkloadNodeSelectorMatch.DeepCopyInto(&out.WorkloadNodeSelectorMatch)
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]v1.TolerationOperator, len(*in))
		copy(*out, *in)
	}
	if in.Effects != nil {
		in, out := &in.Effects, &out.Effects
		*out = make([]v1.TaintEffect, len(*in))
		copy(*out, *in)
	}
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(TolerationDurationMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTolerationMatch.
func (in *WorkloadTolerationMatch) DeepCopy() *WorkloadTolerationMatch {
	if in == nil {
		return nil
	}
	out := new(WorkloadTolerationMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTopologySpreadMatch) DeepCopyInto(out *WorkloadTopologySpreadMatch) {
	*out = *in
	if in.TopologyKey != nil {
		in, out := &in.TopologyKey, &out.TopologyKey
		*out = new(PlacementExpressionMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.WhenUnsatisfiable != nil {
		in, out := &in.WhenUnsatisfiable, &out.WhenUnsatisfiable
		*out = make([]v1.UnsatisfiableConstraintAction, len(*in))
		copy(*out, *in)
	}
	if in.MaxSkew != nil {
		in, out := &in.MaxSkew, &out.MaxSkew
		*out = new(PlacementRange)
		(*in).DeepCopyInto(*out)
	}
	if in.MinDomains != nil {
		in, out := &in.MinDomains, &out.MinDomains
		*out = new(PlacementRange)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAffinityPolicy != nil {
		in, out := &in.NodeAffinityPolicy, &out.NodeAffinityPolicy
		*out = make([]v1.NodeInclusionPolicy, len(*in))
		copy(*out, *in)
	}
	if in.NodeTaintsPolicy != nil {
		in, out := &in.NodeTaintsPolicy, &out.NodeTaintsPolicy
		*out = make([]v1.NodeInclusionPolicy, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(PlacementLabelSelectorMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTopologySpreadMatch.
func (in *WorkloadTopologySpreadMatch) DeepCopy() *WorkloadTopologySpreadMatch {
	if in == nil {
		return nil
	}
	out := new(WorkloadTopologySpreadMatch)
	in.DeepCopyInto(out)
	return out
}
