apiVersion: capsule.clastix.io/v1beta2
kind: ResourceQuotaClaim
metadata:
  labels:
    app.kubernetes.io/name: capsule
    app.kubernetes.io/managed-by: kustomize
  name: resourcequotaclaim-sample
spec:
  # TODO(user): Add fields here
