//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package runtime

import (
	pkgruntime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionMatch) DeepCopyInto(out *ExpressionMatch) {
	*out = *in
	out.ExpressionRegex = in.ExpressionRegex
	if in.Exact != nil {
		in, out := &in.Exact, &out.Exact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionMatch.
func (in *ExpressionMatch) DeepCopy() *ExpressionMatch {
	if in == nil {
		return nil
	}
	out := new(ExpressionMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONSchemaFormExtension) DeepCopyInto(out *JSONSchemaFormExtension) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(KubernetesResourceFormSource)
		**out = **in
	}
	if in.Option != nil {
		in, out := &in.Option, &out.Option
		*out = new(KubernetesResourceFormOption)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONSchemaFormExtension.
func (in *JSONSchemaFormExtension) DeepCopy() *JSONSchemaFormExtension {
	if in == nil {
		return nil
	}
	out := new(JSONSchemaFormExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesResourceFormOption) DeepCopyInto(out *KubernetesResourceFormOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesResourceFormOption.
func (in *KubernetesResourceFormOption) DeepCopy() *KubernetesResourceFormOption {
	if in == nil {
		return nil
	}
	out := new(KubernetesResourceFormOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesResourceFormSource) DeepCopyInto(out *KubernetesResourceFormSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesResourceFormSource.
func (in *KubernetesResourceFormSource) DeepCopy() *KubernetesResourceFormSource {
	if in == nil {
		return nil
	}
	out := new(KubernetesResourceFormSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedResource) DeepCopyInto(out *RenderedResource) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]pkgruntime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedResource.
func (in *RenderedResource) DeepCopy() *RenderedResource {
	if in == nil {
		return nil
	}
	out := new(RenderedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTemplate) DeepCopyInto(out *ResourceTemplate) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]pkgruntime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTemplate.
func (in *ResourceTemplate) DeepCopy() *ResourceTemplate {
	if in == nil {
		return nil
	}
	out := new(ResourceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTemplatePolicy) DeepCopyInto(out *ResourceTemplatePolicy) {
	*out = *in
	if in.Protect != nil {
		in, out := &in.Protect, &out.Protect
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTemplatePolicy.
func (in *ResourceTemplatePolicy) DeepCopy() *ResourceTemplatePolicy {
	if in == nil {
		return nil
	}
	out := new(ResourceTemplatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionKind) DeepCopyInto(out *VersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionKind.
func (in *VersionKind) DeepCopy() *VersionKind {
	if in == nil {
		return nil
	}
	out := new(VersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionKinds) DeepCopyInto(out *VersionKinds) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionKinds.
func (in *VersionKinds) DeepCopy() *VersionKinds {
	if in == nil {
		return nil
	}
	out := new(VersionKinds)
	in.DeepCopyInto(out)
	return out
}
