//go:build !ignore_autogenerated

// Copyright 2020-2023 Project Capsule Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package runtime

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionMatch) DeepCopyInto(out *ExpressionMatch) {
	*out = *in
	out.ExpressionRegex = in.ExpressionRegex
	if in.Exact != nil {
		in, out := &in.Exact, &out.Exact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionMatch.
func (in *ExpressionMatch) DeepCopy() *ExpressionMatch {
	if in == nil {
		return nil
	}
	out := new(ExpressionMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionKind) DeepCopyInto(out *VersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionKind.
func (in *VersionKind) DeepCopy() *VersionKind {
	if in == nil {
		return nil
	}
	out := new(VersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionKinds) DeepCopyInto(out *VersionKinds) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionKinds.
func (in *VersionKinds) DeepCopy() *VersionKinds {
	if in == nil {
		return nil
	}
	out := new(VersionKinds)
	in.DeepCopyInto(out)
	return out
}
