{{- if and (not $.Values.crds.exclusive) $.Values.global.jobs.postDelete.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capsule.post-delete.name" . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-4"
    {{- include "capsule.post-delete.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capsule.post-delete.component" . | quote }}
    app.kubernetes.io/name: {{ include "capsule.post-delete.component" . | quote }}
    {{- include "capsule.baselabels" . | nindent 4 }}
    {{- include "capsule.selectorLabelInstance" . | nindent 4 }}
{{- end }}
