---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalResourceQuota
metadata:
  name: green-shared-compute
  labels:
    projectcapsule.dev/tenant: green
spec:
  namespaceSelectors:
    - matchLabels:
        capsule.clastix.io/tenant: green
  quota:
    hard:
      limits.cpu: "0"
      limits.memory: 16Gi
      requests.cpu: "8"
      requests.memory: 16Gi
