---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15s
  timeout: 10m
  targetNamespace: cert-manager
  releaseName: "cert-manager"
  chart:
    spec:
      chart: cert-manager
      version: "1.19.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: -1
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://charts.jetstack.io
