{
 "title": "Capsule / ResourcePools",
 "description": "Administrative Overview for ResourcePools",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource",
    "label": "Resource",
    "query": {
     "query": "label_values(capsule_pool_resource,resource)"
    }
   },
   {
    "name": "resourcepool",
    "label": "ResourcePool",
    "query": {
     "query": "label_values(capsule_pool_resource{resource=~\"$resource\"},pool)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ResourcePools",
   "type": "stat",
   "description": "Amount of ResourcesPools providing the given resources",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pool) (capsule_pool_resource{pool=~\"$resourcepool\", resource=~\"$resource\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Claim Overview",
   "type": "table",
   "description": "Overview of claims",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "capsule_claim_condition{pool=~\"$resourcepool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (capsule_claim_condition))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bound Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims successfully bound to ResourcePools",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (\n  capsule_claim_condition{condition=\"Bound\"} == 1\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims with no ResourcePool associated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (\n  capsule_claim_condition{pool=\"\"}\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool $resourcepool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "resourcepool" },
  {
   "title": "Resource Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capsule_pool_usage_percentage{pool=~\"$resourcepool\", resource=~\"$resource\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (resource) ( capsule_pool_usage_percentage{pool=~\"$resourcepool\", resource=~\"$resource\"} )",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Total Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (capsule_claim_condition{pool=~\"$resourcepool\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Claim Overview",
   "type": "table",
   "description": "Overview of claims",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "capsule_claim_condition{pool=~\"$resourcepool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bound Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims successfully bound",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (\n  capsule_claim_condition{pool=~\"$resourcepool\",condition=\"Bound\"} == 1\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Claims",
   "type": "stat",
   "description": "Amount of ResourcesPoolsClaims successfully bound",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name, namespace) (\n  capsule_claim_condition{pool=~\"$resourcepool\",condition=\"Bound\"} == 0\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exhaustions/Overprovisioning",
   "type": "table",
   "description": "Pool Exhaustions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (resource) (\n  capsule_pool_exhaustion{pool=~\"$resourcepool\", resource=~\"$resource\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (resource) (\n  capsule_pool_available{pool=~\"$resourcepool\", resource=~\"$resource\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exhaustions/Overprovisioning (%)",
   "type": "timeseries",
   "description": "Pool Exhaustions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "capsule_pool_exhaustion_percentage{pool=~\"$resourcepool\", resource=~\"$resource\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "$resource (Namespaces)",
   "type": "piechart",
   "description": "Allocation distribution amongst namespaces",
   "gridPos": { "h": 9, "w": 4.8, "x": 0, "y": 44 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capsule_pool_namespace_usage_percentage{pool=~\"$resourcepool\", resource=~\"$resource\"}",
     "legendFormat": "{{target_namespace}}"
    }
   ]
  }
 ]
}