apiVersion: v1
type: postrenderer/v1
name: capsule-playground
version: 0.1.0
runtime: subprocess
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/../../scripts/capsule-post-renderer.sh
