---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
  labels:
    customer: a
spec:
  owners:
  - name: alice
    kind: User
  rules:
    - permissions:
        promotions:
          - clusterRoles:
            - "configmap-replicator"
    - namespaceSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - "test"
      permissions:
        promotions:
          - clusterRoles:
            - "secret-replicator"
    - namespaceSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - "prod"
      permissions:
        promotions:
          - clusterRoles:
            - "sade-boi"
  permissions:
    matchOwners:
    - matchLabels:
        team: platform
    - matchLabels:
        tenant: solar
  namespaceOptions:
    additionalMetadata:
      labels:
        team: platform
      annotations:
        owner: "team-platform"
    additionalMetadataList:
      - labels:
          customer: a
  additionalRoleBindings:
  - clusterRoleName: 'view'
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: User
      name: joe
  resourceQuotas:
    scope: Tenant
    items:
    - hard:
        limits.cpu: "8"
        limits.memory: 16Gi
        requests.cpu: "8"
        requests.memory: 16Gi
    - hard:
        pods: "10"
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: green
  labels:
    customer: a
spec:
  permissions:
    matchOwners:
    - matchLabels:
        team: devops
    - matchLabels:
        tenant: green
  owners:
  - name: bob
    kind: User
  additionalRoleBindings:
  - clusterRoleName: 'view'
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: User
      name: alice
  rules:
    - permissions:
        promotions:
          - clusterRoles:
            - "admin"
            selector:
              matchLabels:
                owner.projectcapsule.dev/role: "replication"

    - enforce:
        action: "allow"
        workloads:
          registries:
          - exp: ".*"
    - enforce:
        action: "deny"
        workloads:
          registries:
          - exp: "harbor/.*"
    - enforce:
        action: "deny"
        workloads:
          registries:
          - exp: "harbor/customer/.*"
    - namespaceSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
            - "prod"
      enforce:
        action: "allow"
        workloads:
          registries:
          - exp: "harbor/customer/prod-image/.*"
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: wind
spec:
  permissions:
    matchOwners:
    - matchLabels:
        team: devops
    - matchLabels:
        tenant: wind
  owners:
  - name: joe
    kind: User
  additionalRoleBindings:
  - clusterRoleName: 'view'
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: wind-users
