---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
  labels:
    customer: a
spec:
  owners:
  - name: alice
    kind: User
  rules:
    - permissions:
        bindings:
          - clusterRoleName: 'custom:proxy-viewer'
            subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: joe
            labels:
              reflection.proxy.projectcapsule.dev/enabled: "true"
      enforce:
        action: deny
        metadata:
          - apiGroups:
              - "v1"
            kinds:
              - "Namespace"
            labels:
              pod-security.kubernetes.io/enforce:
                managed: "restricted"
          #- apiGroups:
          #    - "v1"
          #  kinds:
          #    - "*"
          #  labels:
          #    custom.corp/tenant:
          #      managed: "{{ $.tenant.metadata.name }}"
          #    test: 
          #      managed: "true"
    - audience:
        - kind: "Custom"
          name: "CapsuleUser"
      enforce:
        action: deny
        metadata:
          - apiGroups:
              - "v1"
            kinds:
              - "Namespace"
            labels:
              "openshift.io/*":
                required: false
                values:
                  - exp:  "^.*$"
    - namespaceSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - "test"
      permissions:
        promotions:
          - clusterRoles:
            - "secret-replicator"
    - namespaceSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - "prod"
      permissions:
        promotions:
          - clusterRoles:
            - "sade-boi"
  permissions:
    matchOwners:
    - matchLabels:
        team: platform
    - matchLabels:
        tenant: solar
  namespaceOptions:
    additionalMetadata:
      labels:
        team: platform
      annotations:
        owner: "team-platform"
    additionalMetadataList:
      - labels:
          customer: a
  resourceQuotas:
    scope: Tenant
    items:
    - hard:
        limits.cpu: "8"
        limits.memory: 16Gi
        requests.cpu: "8"
        requests.memory: 16Gi
    - hard:
        pods: "10"
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: green
  labels:
    customer: a
spec:
  permissions:
    matchOwners:
    - matchLabels:
        team: devops
    - matchLabels:
        tenant: green
  owners:
  - name: bob
    kind: User
  rules:
  - permissions:
      bindings:
        - clusterRoleName: 'custom:proxy-viewer'
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: alice
          labels:
            reflection.proxy.projectcapsule.dev/enabled: "true"

  - enforce:
      action: "allow"
      services:
        types: ["ClusterIP", "NodePort", "LoadBalancer", "ExternalName"]
        loadBalancers:
          cidrs:
            - 10.0.0.2/32
        externalNames:
          hostnames:
            - exp: ".*\\.example\\.com"
              exact:
                - "internal.git.com"
        nodePorts:
          ports:
            - from: 30000
              to: 32767
  - enforce:
      action: "allow"
      # generic:
      #   - kinds:
      #       - "ConfigMap"
      #     path: ".data.key"
      #     entity: "Any/TenantOwner/CapsuleUser"
      #     operator: "Equals/Truthy"
      #     values:
      #       - exact:
      #         - "sad"
      #         from: ".status.classes.ingress"
      metadata:
        - kinds:
            - "ConfigMap"
          labels:
            "corp.com/tenant":
              required: true
              values:
                - exact:
                    - test
          annotations:
            "example.corp/cost-center":
              required: true
              values:
                - exp: "^INV-[0-9]{4}$"
                  exact:
                    - prod
                    - test
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: wind
spec:
  permissions:
    matchOwners:
    - matchLabels:
        team: devops
    - matchLabels:
        tenant: wind
  owners:
  - name: joe
    kind: User
  rules:
  - permissions:
      bindings:
        - clusterRoleName: 'view'
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: wind-users
