apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - owner-alice.yaml
  - owner-bob.yaml
  - owner-gatsby.yaml
  - owner-devops.yaml
  - owner-platform-admin.yaml
  - owner-renewable.yaml
